import { createFileRoute } from "@tanstack/react-router";
import { Bar, Panel, Sparkline, Stat, StatusDot, Tag } from "@/components/demo/primitives";
import { health, hostDisk, trafficSeries } from "@/data/seed";
import { pct } from "@/lib/format";
import { B } from "@/lib/brand";

export const Route = createFileRoute("/demo/health")({ head: () => ({ meta: [{ title: `Service health — ${B.name} demo` }, { name: "description", content: "Runtime health for the Node services running observed operations." }, { property: "og:title", content: `Service health — ${B.name}` }, { property: "og:description", content: "CPU, memory, event-loop delay, uptime, and storage health." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: HealthPage });

function HealthPage() { const degraded = health.filter(s => s.status === "degraded").length; return <div className="space-y-4"><header><h1 className="text-[17px] font-semibold">Health</h1><p className="mt-0.5 text-[12.5px] text-muted-foreground">Runtime signals for services that execute observed operations.</p></header><div className="grid gap-3 sm:grid-cols-3"><Stat label="Services" value={health.length} hint={`${health.length - degraded} healthy`} /><Stat label="Degraded" value={degraded} tone={degraded ? "warn" : "ok"} hint="worker memory pressure" /><Stat label="Data file" value={`${hostDisk.dbSizeGb} GB`} hint={hostDisk.dataFile} /></div><div className="grid gap-3 lg:grid-cols-3">{health.map(s => <Panel key={s.service} title={<span className="flex items-center gap-2"><StatusDot status={s.status} />{s.service}</span>} action={<Tag tone={s.status === "healthy" ? "ok" : "warn"}>{s.status}</Tag>}><dl className="space-y-3"><HealthMetric label="CPU" value={pct(s.cpu, 0)} amount={s.cpu} tone={s.cpu > .7 ? "warn" : "primary"} /><HealthMetric label="Memory" value={`${s.memoryMb} / ${s.memoryLimitMb} MB`} amount={s.memoryMb / s.memoryLimitMb} tone={s.memoryMb / s.memoryLimitMb > .8 ? "warn" : "primary"} /><div className="grid grid-cols-3 gap-2 border-t border-border/60 pt-3 text-center"><Mini label="Event loop" value={`${s.eventLoopLagMs}ms`} /><Mini label="Restarts" value={String(s.restarts)} /><Mini label="Instances" value={String(s.instances)} /></div><div className="text-[11px] text-muted-foreground">uptime <span className="num text-foreground">{s.uptime}</span></div></dl></Panel>)}</div><div className="grid gap-3 lg:grid-cols-2"><Panel title="Host storage" subtitle={hostDisk.dataFile}><div className="flex items-end justify-between"><div><span className="num text-2xl">{hostDisk.usedGb} GB</span><span className="text-xs text-muted-foreground"> / {hostDisk.totalGb} GB</span></div><span className="num text-xs text-muted-foreground">{pct(hostDisk.usedGb / hostDisk.totalGb, 0)} used</span></div><Bar value={hostDisk.usedGb / hostDisk.totalGb} className="mt-3" /></Panel><Panel title="Ingest activity" subtitle="accepted occurrences per hour"><Sparkline data={trafficSeries} /></Panel></div></div>; }

function HealthMetric({ label, value, amount, tone }: { label: string; value: string; amount: number; tone: "primary" | "warn" }) { return <div><div className="flex justify-between text-[11.5px]"><dt className="text-muted-foreground">{label}</dt><dd className="num">{value}</dd></div><Bar value={amount} tone={tone} className="mt-1.5" /></div>; }
function Mini({ label, value }: { label: string; value: string }) { return <div><dt className="text-[10px] text-muted-foreground">{label}</dt><dd className="num mt-1 text-[12px]">{value}</dd></div>; }