import { createFileRoute, Link } from "@tanstack/react-router";
import { Panel, Stat, TableShell, Tag } from "@/components/demo/primitives";
import { useFilters } from "@/components/demo/filters";
import { securityEvents, securityRoutes } from "@/data/seed";
import { num, scale } from "@/lib/format";
import { B } from "@/lib/brand";

export const Route = createFileRoute("/demo/security")({ head: () => ({ meta: [{ title: `Security signals — ${B.name} demo` }, { name: "description", content: "Review authentication failures and explicitly reported security events on marked routes." }, { property: "og:title", content: `Security signals — ${B.name}` }, { property: "og:description", content: "Focused security context without becoming a SIEM." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: SecurityPage });

function SecurityPage() { const { factor } = useFilters(); const unauthorized = securityRoutes.reduce((s,r) => s + r.unauthorized, 0); const forbidden = securityRoutes.reduce((s,r) => s + r.forbidden, 0); return <div className="space-y-4"><header><h1 className="text-[17px] font-semibold">Security</h1><p className="mt-0.5 text-[12.5px] text-muted-foreground">Auth failures and events from observed routes. This is a focused signal, not a SIEM.</p></header><div className="grid gap-3 sm:grid-cols-3"><Stat label="Unauthorized" value={num(scale(unauthorized, factor))} tone="danger" hint="401 responses" /><Stat label="Forbidden" value={num(scale(forbidden, factor))} tone="warn" hint="403 responses" /><Stat label="Reported events" value={num(scale(securityEvents.filter(e => e.kind === "reported").length, factor))} hint="explicit events" /></div><Panel title="Routes with auth failures" bodyClassName="px-0 py-0"><TableShell head={<><th className="px-4 py-2 font-medium">Route</th><th className="px-4 py-2 font-medium">Service</th><th className="px-4 py-2 text-right font-medium">401</th><th className="px-4 py-2 text-right font-medium">403</th></>}>{securityRoutes.map(r => <tr key={r.route} className="border-b border-border/60 last:border-0"><td className="px-4 py-2.5 font-mono text-[12px]">{r.route}</td><td className="px-4 py-2.5"><Tag>{r.service}</Tag></td><td className="num px-4 py-2.5 text-right text-danger">{num(scale(r.unauthorized, factor))}</td><td className="num px-4 py-2.5 text-right text-warn">{num(scale(r.forbidden, factor))}</td></tr>)}</TableShell></Panel><Panel title="Recent security events" subtitle="Occurrence links are available when the route is observed">{securityEvents.map(e => <div key={e.id} className="grid gap-2 border-b border-border/60 py-3 first:pt-0 last:border-0 last:pb-0 sm:grid-cols-[120px_1fr_auto]"><div><Tag tone={e.kind === "reported" ? "meter" : e.kind === "forbidden" ? "warn" : "danger"}>{e.code}</Tag><div className="num mt-1 text-[10.5px] text-muted-foreground">{e.when}</div></div><div className="min-w-0"><p className="font-mono text-[12px]">{e.method} {e.route}</p><p className="truncate text-[11.5px] text-muted-foreground">{e.note}</p><p className="mt-0.5 font-mono text-[10.5px] text-muted-foreground">{e.ip}{e.tenant ? ` · ${e.tenant}` : ""}</p></div>{e.occurrenceId ? <Link to="/demo/occurrences/$id" params={{ id: e.occurrenceId }} className="font-mono text-[11px] text-primary hover:underline">view occurrence</Link> : <span />}</div>)}</Panel></div>; }